version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - db_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer  
    ports:
      - "8080:8080" 
    depends_on:
      - db  

volumes:
  db_storage: 
